課題3提出一回目
ryoma-yama/markup_kadai_03 pull request #1
Opened 2020-03-09 09:46 UTC by ryoma-yama

### やったこと

- positionプロパティで絶対配置を指定して青色を赤色に重ねました。
- 課題とは関係ありませんが、練習をかねてdivの属性をidからclassにしました。

2020-03-10 06:14 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-03-10 06:14 UTC, piasoratech commented on style.css
> +  background-color: #f00;
色の指定が異なっているので修正しましょう。
(カリキュラムに指定があります。)

2020-03-10 08:51 UTC, ryoma-yama commented
3a58ca5 指摘のあった色指定を修正しました。

2020-03-26 02:31 UTC, ryoma-yama commented
3e4d07a と d153513 にてクラス名を変更しました。

2020-03-31 16:21 UTC, piasoratech approved these changes
OKです！

2020-04-18 00:30 UTC, merged